#!/bin/bash
# Emergency shutdown stick
# Fedora 23 version

KEYWORDS='(c52b)'  # add your own keywords

fifo=$(mktemp).$$
mkfifo "${fifo}" || exit 1
nb_positives=$(dmesg | grep -E -i -c "${KEYWORDS}")
nb_positives=$(($nb_positives + 1))

dmesg -w >${fifo} &
grep -E -i -m "${nb_positives}" "${KEYWORDS}" "${fifo}" > /dev/null

#sync  # uncomment me if you want

# Trash RAM and shutdown everything
#sdmem -fll
poweroff -f
